name: KMP library compilation check

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Check runtime
        run: ./local-check.sh
      - name: Check sample
        run: cd sample && ./local-check.sh
